### ISSUE TITLE
Electorn Windows Store Build Crashing

### ISSUE THREAD

**Issue by Aashir1** [felixrieseberg/electron-windows-store#119]
Getting error while executing this command : 
`electron-windows-store --input-directory ./dist --output-directory ./output --package-version 1.0.0.0   --package-name cra-electron`
You can see I provide all required arguments --input-directory, --output-directory, --package-version and --package-name except  --flatten because its no more required according to this commit [https://github.com/felixrieseberg/electron-windows-store/commit/dcc654df2ec2bb706dc4f1664aa4775ab320541e](https://github.com/felixrieseberg/electron-windows-store/commit/dcc654df2ec2bb706dc4f1664aa4775ab320541e)

**Error**
`Configuration:`
`Desktop Converter Location: C:\ProgramFiles\WindowsApps\Microsoft.DesktopAppConverter_2.1.4.0_x64__8wekyb3d8bbwe`
`Expanded Base Image: C:\Users\xxx\Downloads\Windows_BaseImage_DAC_18362_V1.wim`
`Publisher:  CN=developmentca`
`Dev Certificate:  C:\Users\xxx\AppData\Roaming\electron-windows-store\developmentca\developmentca.pfx`
`Windows Kit Location:          C:\Program Files (x86)\Windows Kits\10\bin\x64`

`? Please enter the path to your built Electron app:  ./dist`
`? Please enter the path to your output directory:  ./output./output`
`? Please enter the path to your output directory:  ./output`
`? Please enter your app's package name (name of your exe - without '.exe'):  cra-electron`
`? Please enter your app's package version:  1.0.0.0`
`Starting Conversion...`
`Cleaning pre-appx output folder...`
`Copying data...`
`Creating manifest..`
`Creating appx package...`
`events.js:174`
     ` throw er; // Unhandled 'error' event`
      `^`

`Error: spawn C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe ENOENT`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)`
`    at onErrorNT (internal/child_process.js:415:16)`
 `   at process._tickCallback (internal/process/next_tick.js:63:19)`
`Emitted 'error' event at:`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)`
`    at onErrorNT (internal/child_process.js:415:16)`
`    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by kirillgalushko** [comment]
@Aashir1 Are you sure that your windows kit is `C:\Program Files (x86)\Windows Kits\10\bin\x64`?
I met the same problem and resolved it with the argument:
`--windows-kit "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64"`

**Comment by JonoDNelson** [comment]
Just to add to @kirillgalushko 's answer, You can't have a trailing '\' after the 'x64' in the path.
