### ISSUE TITLE
Identity Setup - Type Error - Windows Kit folder

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#36]
`electron-windows-store` quits with an `TypeError` during first use.

> You need to install a development certificate ... (Y/n)
> Y
> Welcome to the Electron-Windows-Store tool!
> ...
> Please enter the location of your Windows Kit's bin folder: (C:\Program Files (x86)\Windows\Kits\10\bin\x64)
hit enter =>

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    ...
    at inquirer.prompt.then (...lib\setup.js:161:31)
```

Also happens when actually entering the path. I'm on a 32 bit machine - also tried `C:\Program Files (x86)\Windows\Kits\10\bin\x86`.

// edit
When I look at `setup.js:161` this might be an issue w/ the input for the `publisher identity`. I entered two words (don't know yet what exactly goes in there).

node v6.2.1
npm 3.10.2

// edit 2:

`setup.js:160` is the issue:
```javascript
let publisher = dotfile.get().publisher.split('=')[1]
```
There's nothing to `split` as `dotfile.get()` returns an object and `publisher` already contains the actual content. That leads me to the thought that my input might be invalid.
**What exatly goes into the identity prompt?**

Guess those lines could use some extra explanation + some more robustness.

**Comment by black-snow** [comment]
Guess the input should be something like `CN=whatever`
