### ISSUE TITLE
Unknown error, events.js:160

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#42]
Ran `electron-windows-store` inside my `build` folder. Stepped through the questions:

* appconverter: n
* certificate: n
* publisher id: ...
* windows kit location: ...
* path to built app: ./path/to/my/packaged/app
* output path: default
* flattening: y
* package name: the name of the exe
* version: 0.9.13.0

It then starts flattening etc., starting conversion, cleaning output folder, copying data, and after printing `Creating manifest..` this is what happens:

```
events.js:160
    throw er; // Unhandled 'error' event
    ^

Error: spawn ...x86\makeappx.exe ENOENT
    ...
```

Can't tell what went wrong. Any way to debug this?

**Comment by felixrieseberg** [comment]
We apparently have trouble finding the `makeappx` binary. Let me dig for a moment, but this should be totally fixable.

**Comment by felixrieseberg** [comment]
Looking at the code, I sadly couldn't find anything super obvious. Could you do me a favor and check where exactly `makeappx.exe` is on your machine?

**Comment by black-snow** [comment]
Sure, will do tomorrow (Europe/Berlin).

**Comment by black-snow** [comment]
@felixrieseberg `makeappx.exe` is at `C:\Program Files\Windows Kits\10\bin\x86` instead of `C:\Program Files (x86)\Windows Kits\10\bin\x86`.

Works using `C:\Program Files\Windows Kits\10\bin\x86`.

Should we modify the default path?

**Comment by clusterberries** [comment]
For me this path looks like `C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64`

**Comment by rptwsthi** [comment]
Any thing on this thread, when I try to execute:


electron-windows-store `
    --input-directory D:\Arpit\GSWindows\GSLive\GSDesktop `
    --output-directory D:\Output `
    --package-version 1.0.0.0 `
    --package-name GSDesktop

Inside `WindowsPowerCell` it gives same error:

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)

**Comment by rptwsthi** [comment]
Updated my request to this:

**Comment by rptwsthi** [comment]
Updated my request to this and all worked out:

electron-windows-store `
    --input-directory D:\Arpit\GSWindows\GSLive\GoSesstionDesktop `
    --output-directory D:\Output `
    --package-version 1.0.0.0 `
    --windows-kit 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit' `
    --desktop-converter 'C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppConverter_8wekyb3d8bbwe' `
    --publisher CN=IfConditions `
    --package-name GoSession

**Comment by rptwsthi** [comment]
> Updated my request to this and all worked out:
> 
> electron-windows-store --input-directory D:\Arpit\GSWindows\GSLive\GoSesstionDesktop
> --output-directory D:\Output --package-version 1.0.0.0
> --windows-kit 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit' --desktop-converter 'C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppConverter_8wekyb3d8bbwe'
> --publisher CN=IfConditions `
> --package-name GoSession

**Comment by rptwsthi** [comment]
Now I am facing another issue, though the package is created yet I am not able to install the using this : Package as there is some issue with certificate.

Package creation succeeded.

Error information: "Error: Store IsDiskFile() failed." (-2147024893/0x80070003)

SignTool Error: An unexpected internal error has occurred.

Error: C:\Program Files (x86)\Windows Kits\10\App Ce

> rtification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> Error: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> PS D:\Arpit\GSWindows\GSLive\GoSesstionDesktop>

**Comment by MysticCraftYT** [comment]
I got the same issue too, idk why

**Comment by nfplay** [comment]
@rptwsthi  and @MysticCraftYT , at this time you've probably already guessed that you're missing the path to your pfx developer certificate using the option '--dev-cert' :)
