### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by utiq** [felixrieseberg/electron-windows-store#91]
I get this error when I try to use the command, any advice?
```
Flattening modules...
Starting Conversion...
Cleaning pre-appx output folder...
Copying data...
Creating manifest..
Creating appx package...
{ Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at Object.exports.spawn (child_process.js:369:9)
    at Promise (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:67:44)
    at Object.executeChildProcess (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:6
6:10)
    at Promise (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\makeappx.js:34:18)
    at module.exports (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\makeappx.js:8:10)
    at setup.then.then.then.then.then.then.then.then (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-s
tore\bin\windowsstore.js:83:15) code: 'UNKNOWN', errno: 'UNKNOWN', syscall: 'spawn' }
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at Object.exports.spawn (child_process.js:369:9)
    at Promise (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:67:44)
    at Object.executeChildProcess (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:6
6:10)
    at Promise (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\makeappx.js:34:18)
    at module.exports (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-store\lib\makeappx.js:8:10)
    at setup.then.then.then.then.then.then.then.then (C:\Users\Cesar\AppData\Roaming\npm\node_modules\electron-windows-s
tore\bin\windowsstore.js:83:15)
```

**Comment by felixrieseberg** [comment]
You seem to be missing the Windows SDK - in particular, makeappx.exe.

**Comment by utiq** [comment]
How can I change the .electron-windows-store file details? I cannot find the file. This is how mine is configured, and I think 'Windows Kit Location' is not the right path.

```
Configuration:
Desktop Converter Location:    C:\Program Files\WindowsApps\Microsoft.DesktopAppConverter_2.1.0.0_x64__8wekyb3d8bbwe
Expanded Base Image:           C:\Users\Cesar\Downloads
Publisher:                     publisher.com
Dev Certificate:               C:\Users\Cesar\Downloads\certificates\publisher.com.pfx
Windows Kit Location:          C:\Program Files (x86)\Windows Kits\10\bin\x64
```
