### ISSUE TITLE
Error signing

### ISSUE THREAD

**Issue by yoprogramo** [felixrieseberg/electron-windows-store#94]
In two different projects with electron I  tried to generate the appx  with the same error:

`The following certificates were considered:

    Issued to: Biblioeteca Technologies SL
    Issued by: Symantec Class 3 SHA256 Code Signing CA
    Expires:   Wed Oct 03 00:59:59 2018
    SHA1 hash: D817E23E0E21B7D46A5F629E92818EACDB1D341D

After EKU filter, 1 certs were left.
After expiry filter, 1 certs were left.
After Private Key filter, 1 certs were left.
The following certificate was selected:
    Issued to: Biblioeteca Technologies SL
    Issued by: Symantec Class 3 SHA256 Code Signing CA
    Expires:   Wed Oct 03 00:59:59 2018
    SHA1 hash: D817E23E0E21B7D46A5F629E92818EACDB1D341D

The following additional certificates will be attached:

    Issued to: Symantec Class 3 SHA256 Code Signing CA
    Issued by: VeriSign Class 3 Public Primary Certification Authority - G5
    Expires:   Sun Dec 10 00:59:59 2023
    SHA1 hash: 007790F6561DAD89B0BCD85585762495E358F8A5

Done Adding Additional Store

Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)

SignTool Error: An unexpected internal error has occurred.

Error: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe exited with code: 1
    at ChildProcess.child.on (C:\Users\bibli\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Error: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe exited with code: 1
    at ChildProcess.child.on (C:\Users\bibli\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`

Some clue?

**Comment by gilvandev** [comment]
For me:

`Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)

SignTool Error: An unexpected internal error has occurred.

(node:4124) UnhandledPromiseRejectionWarning: Error: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe exited with code: 1
    at ChildProcess.child.on (D:\Apps\OS\front\node_modules\electron-windows-store\lib\utils.js:74:23)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:4124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by taxilian** [comment]
Has anyone figured this out? Mine was working, now it's not, same error as the first person -- on two different machines. can't figure out what is going on, tried different keys, tried reconfiguring... nothing.

**Comment by felixrieseberg** [comment]
I'm sorry to hear that, but I'm afraid that the problem has likely very little to do with this module. We just call `signtool.exe` and _hope_ that it'll do the right thing. 

I'll leave the issue open as other people will surely find it, but there's not much I can do 😢

**Comment by taxilian** [comment]
So I finally figured out what it was with mine; I have no idea how it was working and stopped, but it turned out I had two certificates and misunderstood what I should be looking at. My publisher (CN=) in the app manifest was some hex number and that actually matched one of my certificates but not the one I thought it was.

From my research this is 95% sure (that's a totally legit statistic that I just made up) that this issue is related to a publisher mismatch between the manifest and the certificate.
